### ISSUE TITLE
Running BLINKER on EPOCHS

### ISSUE THREAD

**Issue by jortega003** [VisLab/EEG-Blinks#5]
Hello,

I am very interested in running BLINKER on epoched data. Is this currently possible? I have searched through the plugin and couldn't find an answer.

Many thanks in advance,

Jefferson

**Comment by VisLab** [comment]
Sorry, you can't run blinker on epochs --- it assumes continuous data, of at least 10 minutes.  The best thing is to run on the raw data and save the event markers before epoching.

**Comment by jortega003** [comment]
Thank you for your response and for the advice!
