### ISSUE TITLE
Problem initializing eyeCatch in getCandidateICs()

### ISSUE THREAD

**Issue by halprad** [VisLab/EEG-Blinks#8]
The code in version 1.1.3 of the toolbox can only initialize eyeCatch if it's part of the measurement projection toolbox as follows:

eyeDetector = pr.eyeCatch;

Perhaps changing this initialization to something like the following code would fix this issue:

try
    eyeDetector = pr.eyeCatch;
catch
    eyeDetector = eyeCatch;
end

**Comment by VisLab** [comment]
Thanks for the heads up.  I realize that eyeCatch is no longer easily available.  I will do a new release with it packaged.

**Comment by VisLab** [comment]
Commit [50fb621](https://github.com/VisLab/EEG-Blinks/commit/50fb6212897d98273ca7b5882c69af7a54ba68fc)
embeds eyeCatch in the distribution. A separate zipped EEGLAB plugin is no longer available because of GitHub's file size limitations.
